# Generated by Django 6.0.4 on 2026-04-26 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='encrypted_docs/%Y/%m/%d/')),
                ('original_filename', models.CharField(max_length=255)),
                ('encryption_iv', models.CharField(max_length=24)),
                ('document_type', models.CharField(choices=[('IDENTITY', 'Identity'), ('MEDICAL_RECORD', 'Medical Record'), ('RESULT', 'Result'), ('PRESCRIPTION', 'Prescription'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
